### ISSUE TITLE
Makefile not correct : crt0-$(CPU)-ctr.o vs of crt0-$(CPU)-crt.o

### ISSUE THREAD

**Issue by JC-LL** [enjoy-digital/fpga_101#1]
In the build dir of lab004, the Makefile is not correct : during the build process, we have a file named crt0-$(CPU)-ctr.o instead of crt0-$(CPU)-crt.o as required in the Makefile. 
I know "crt" meaning (runtime), but maybe the extensions "ctr" has a different meaning ?

**Comment by enjoy-digital** [comment]
Thanks, sorry, should be good now: https://github.com/enjoy-digital/fpga_101/commit/6b6fda5195a6cbdf5ac9f896b069b533e72ab6f8.
