### ISSUE TITLE
lab002 display type confusion

### ISSUE THREAD

**Issue by keesj** [enjoy-digital/fpga_101#2]
[lab002/display.py](https://github.com/enjoy-digital/fpga_101/blob/master/lab002/display.py#L28) defines a class called Display however migen also has a [Display defined](https://github.com/m-labs/migen/blob/master/migen/fhdl/structure.py#L760)

As a result the tutorial exists with the following (confusing message) message:

```
 python base.py  
 Traceback (most recent call last):
  File "base.py", line 129, in <module>
    module = Clock()
  File "base.py", line 109, in __init__
    display.values[0].eq(bcd_seconds.ones),
 AttributeError: 'Display' object has no attribute 'values'
```

![selection_190](https://user-images.githubusercontent.com/57112/52785741-096ef500-3059-11e9-94f3-d75ea55bc434.png)

**Comment by enjoy-digital** [comment]
Thanks for the feedback, https://github.com/enjoy-digital/fpga_101/commit/3f8918836f8ffab83f88f5f24c1db78be2cce3ba should solve this.

**Comment by keesj** [comment]
thanks1
